openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/products:
    get:
      summary: 'GET Products.'
      operationId: gETProducts
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'Veum Loop'
                      category:
                        id: 3
                        name: sit
                    -
                      id: 2
                      name: 'Greg Drive'
                      category:
                        id: 8
                        name: id
                    -
                      id: 3
                      name: 'Cummings Trafficway'
                      category:
                        id: 1
                        name: id
                    -
                      id: 4
                      name: 'Zackary Pine'
                      category: null
                    -
                      id: 5
                      name: 'Luettgen Hollow'
                      category:
                        id: 9
                        name: vero
                    -
                      id: 6
                      name: 'Kemmer Spring'
                      category:
                        id: 2
                        name: magnam
                    -
                      id: 7
                      name: 'Kovacek Highway'
                      category: null
                    -
                      id: 8
                      name: 'Abe Drives'
                      category:
                        id: 5
                        name: quos
                    -
                      id: 9
                      name: 'Lexie Heights'
                      category:
                        id: 7
                        name: qui
                    -
                      id: 10
                      name: 'Satterfield Pike'
                      category: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'Veum Loop'
                        category:
                          id: 3
                          name: sit
                      -
                        id: 2
                        name: 'Greg Drive'
                        category:
                          id: 8
                          name: id
                      -
                        id: 3
                        name: 'Cummings Trafficway'
                        category:
                          id: 1
                          name: id
                      -
                        id: 4
                        name: 'Zackary Pine'
                        category: null
                      -
                        id: 5
                        name: 'Luettgen Hollow'
                        category:
                          id: 9
                          name: vero
                      -
                        id: 6
                        name: 'Kemmer Spring'
                        category:
                          id: 2
                          name: magnam
                      -
                        id: 7
                        name: 'Kovacek Highway'
                        category: null
                      -
                        id: 8
                        name: 'Abe Drives'
                        category:
                          id: 5
                          name: quos
                      -
                        id: 9
                        name: 'Lexie Heights'
                        category:
                          id: 7
                          name: qui
                      -
                        id: 10
                        name: 'Satterfield Pike'
                        category: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Veum Loop'
                        category:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 3
                            name:
                              type: string
                              example: sit
      tags:
        - Endpoints
      security: []
    post:
      summary: 'STORE a new product.'
      operationId: sTOREANewProduct
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/products/{id}':
    get:
      summary: 'SHOW the product'
      operationId: sHOWTheProduct
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
    put:
      summary: 'UPDATE the product'
      operationId: uPDATETheProduct
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'DELETE the product'
      operationId: dELETETheProduct
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
